/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mnstandalone;

import io.micronaut.context.ApplicationContext;

public class App {


    public static void main(String[] args) {
        ApplicationContext context = ApplicationContext.run();
    }
}
